### ISSUE TITLE
Make “change format” effect more obvious.

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/image_effects#19]
> One question: I'm assuming, this effect gets moved out of the "Color actions" to a more appropriate place. It's hard to find it there.

@indigoxela  suggestion in #16

**Comment by laryn** [comment]
@indigoxela Do you have a suggestion? Related, here's a D7 issue requesting it be split into its own submodule:

 - https://www.drupal.org/project/imagecache_actions/issues/1247344

**Comment by indigoxela** [comment]
> Do you have a suggestion? Related, here's a D7 issue requesting it be split into its own submodule

I can see now, why this was in the "Color Actions" initially - transparency. But our approach is to switch the type for better performance, which is totally unrelated to color and/or transparency. (Which is why I'd never search for this functionality there.)

IMO there's no existing submodule that fits, all the other ones seem even less appropriate. So... yes, its own submodule makes sense to me.

**Comment by laryn** [comment]
I wonder if this one might fit in the (nearly empty) main level `image effects` module rather than a separate submodule. I'm trying to think of a reason not to do that for simplicity. I see these two as options:

1. Move it into the main level `Image Effects` module. It's always enabled if you use Image Effects.
2. Create a new submodule and make `Color Actions` dependent on it. It's only enabled if you enable it specifically or if you want to enable Color Actions (for transparency needs).

**Comment by indigoxela** [comment]
@laryn I'm fine with either decision. After all, it's your "baby" - just decide what seems reasonable to you. :wink:

**Comment by indigoxela** [comment]
@laryn how about simply changing the name and description of the coloractions module a bit.

Instead of "Image Effects Color Actions" something like "Image Effects Color and Conversion Actions". That way the functionality could stay in that module and there's no problem with dependencies, and people would still find it. At least, I would.

**Comment by laryn** [comment]
I like that, at least for now. Maybe at some point a bigger reorganization would be appropriate but this seems like a good option at present. Thanks for the idea!
